spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.99.138/dianCan?characterEnconding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null
server:
  context-path: /dianCan


wechat:
  mpAppId: wx3f1a9317f76a3389
  mpAppSecret: 744a111a8979d5d4b4ab05c887789e27





